/* DATABASE */
CREATE DATABASE IF NOT EXISTS tasks_manager DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;

/* TABLE TASKS */
CREATE TABLE tasks (
  id INT NOT NULL AUTO_INCREMENT,
  title VARCHAR(50) NOT NULL,
  content VARCHAR(255) NOT NULL,
  is_completed BOOLEAN NOT NULL,
  date_created DATETIME NOT NULL,
  PRIMARY KEY (id)
) ENGINE = InnoDB;